//
// SPDX-FileCopyrightText: Copyright 2023-2024 Arm Limited and/or its affiliates <open-source-office@arm.com>
//
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the License); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an AS IS BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Generated by tosaValidationGenerator for TOSA Specification 0.60.0
// Modify by implementing the constraints.

#include "tosa_require_checks.hpp"

namespace tosa
{
namespace validator
{
namespace checks
{
// Checks for TOSA Specification 0.60.0
void RequireCheck_25jhgrylo2an5(const regor::Operation *op, [[maybe_unused]] const Context &context)
{
    // Operators: ARITHMETIC_RIGHT_SHIFT,
    static constexpr char constraint[] = "REQUIRE((in_out_t == int32_t && 0 <= value2 && value2 <= 31) || (in_out_t == int16_t && 0 <= value2 && value2 <= 15) || (in_out_t == int8_t && 0 <= value2 && value2 <= 7))";
    bool checkOk = true;
    checkOk = (op != nullptr);  // TODO: Implement check
    if ( !checkOk ) throw std::invalid_argument(constraint);
}

void RequireCheck_35z4hcgn21c8p(const regor::Operation *op, [[maybe_unused]] const Context &context)
{
    // Operators: INTDIV,
    static constexpr char constraint[] = "REQUIRE(value2 != 0)";
    bool checkOk = true;
    checkOk = (op != nullptr);  // TODO: Implement check
    if ( !checkOk ) throw std::invalid_argument(constraint);
}

void RequireCheck_2v5c1x79g8j7o(const regor::Operation *op, [[maybe_unused]] const Context &context)
{
    // Operators: INTDIV,
    static constexpr char constraint[] = "REQUIRE((int64_t)value1 / value2 <= maximum<in_out_t>)";
    bool checkOk = true;
    checkOk = (op != nullptr);  // TODO: Implement check
    if ( !checkOk ) throw std::invalid_argument(constraint);
}

void RequireCheck_3k2pr9vozq62t(const regor::Operation *op, [[maybe_unused]] const Context &context)
{
    // Operators: LOGICAL_LEFT_SHIFT, LOGICAL_RIGHT_SHIFT,
    static constexpr char constraint[] = "REQUIRE(0 <= value2 && value2 <= 31)";
    bool checkOk = true;
    checkOk = (op != nullptr);  // TODO: Implement check
    if ( !checkOk ) throw std::invalid_argument(constraint);
}

void RequireCheck_27adsuj7sthvo(const regor::Operation *op, [[maybe_unused]] const Context &context)
{
    // Operators: MUL,
    static constexpr char constraint[] = "REQUIRE(product >= minimum<int32_t> && product <= maximum<int32_t>)";
    bool checkOk = true;
    checkOk = (op != nullptr);  // TODO: Implement check
    if ( !checkOk ) throw std::invalid_argument(constraint);
}

void RequireCheck_3o6eotvyt76cz(const regor::Operation *op, [[maybe_unused]] const Context &context)
{
    // Operators: TABLE,
    static constexpr char constraint[] = "REQUIRE(length(table) == TABLE_SIZE)";
    bool checkOk = true;
    checkOk = (op != nullptr);  // TODO: Implement check
    if ( !checkOk ) throw std::invalid_argument(constraint);
}

void RequireCheck_31n0oq4yculbk(const regor::Operation *op, [[maybe_unused]] const Context &context)
{
    // Operators: GATHER, SCATTER,
    static constexpr char constraint[] = "REQUIRE(0 <= k && k < K)";
    bool checkOk = true;
    checkOk = (op != nullptr);  // TODO: Implement check
    if ( !checkOk ) throw std::invalid_argument(constraint);
}

void RequireCheck_2apk8ly9uthz6(const regor::Operation *op, [[maybe_unused]] const Context &context)
{
    // Operators: SCATTER,
    static constexpr char constraint[] = "REQUIRE(output_modified[n,k,c] == false)";
    bool checkOk = true;
    checkOk = (op != nullptr);  // TODO: Implement check
    if ( !checkOk ) throw std::invalid_argument(constraint);
}

}  // namespace checks
}  // namespace validator
}  // namespace tosa
