; SPDX-FileCopyrightText: Copyright 2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
;
; SPDX-License-Identifier: Apache-2.0

[architecture]
clusters=1
array_dimension=32
dma_alignment=32
tcdm_size=524288
command_staging_size=4096
linebuffer_max_kernel=5
linebuffer_max_stride=2
linebuffer_max_input_width=640
requant_shift_max=31
